/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FreeresourcesRouteImport } from './routes/freeresources'
import { Route as FindjobsRouteImport } from './routes/findjobs'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIdRouteImport } from './routes/blog/$id'

const FreeresourcesRoute = FreeresourcesRouteImport.update({
  id: '/freeresources',
  path: '/freeresources',
  getParentRoute: () => rootRouteImport,
} as any)
const FindjobsRoute = FindjobsRouteImport.update({
  id: '/findjobs',
  path: '/findjobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/findjobs': typeof FindjobsRoute
  '/freeresources': typeof FreeresourcesRoute
  '/blog/$id': typeof BlogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/findjobs': typeof FindjobsRoute
  '/freeresources': typeof FreeresourcesRoute
  '/blog/$id': typeof BlogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/findjobs': typeof FindjobsRoute
  '/freeresources': typeof FreeresourcesRoute
  '/blog/$id': typeof BlogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/findjobs'
    | '/freeresources'
    | '/blog/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/blogs' | '/findjobs' | '/freeresources' | '/blog/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/findjobs'
    | '/freeresources'
    | '/blog/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  FindjobsRoute: typeof FindjobsRoute
  FreeresourcesRoute: typeof FreeresourcesRoute
  BlogIdRoute: typeof BlogIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/freeresources': {
      id: '/freeresources'
      path: '/freeresources'
      fullPath: '/freeresources'
      preLoaderRoute: typeof FreeresourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findjobs': {
      id: '/findjobs'
      path: '/findjobs'
      fullPath: '/findjobs'
      preLoaderRoute: typeof FindjobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  FindjobsRoute: FindjobsRoute,
  FreeresourcesRoute: FreeresourcesRoute,
  BlogIdRoute: BlogIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
